# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'jfrogv2 arti'
    imageName: 'ecosysjfrog.jfrog.io/docker-virtual/redhat/ubi8-micro:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: '123'
    skipLogin: false


- task: JFrogDocker@1
  inputs:
    command: 'Scan'
    xrayConnection: 'jfrog xray token'
    imageName: 'ecosysjfrog.jfrog.io/docker-virtual/redhat/ubi8-micro:latest'
    watchesSource: 'none'
    licenses: true
    allowFailBuild: true
    threads: '3'
    skipLogin: false

- task: JFrogDocker@1
  inputs:
    command: 'Scan'
    xrayConnection: 'jfrog xray token'
    imageName: 'ecosysjfrog.jfrog.io/docker-virtual/redhat/ubi8-micro:latest'
    watchesSource: 'watches'
    watches: 'dasdsa'
    allowFailBuild: true