# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogConan@1
  inputs:
    conanCommand: 'Add Remote'
    remoteName: 'sdfs'
    artifactoryConnection: 'jfrog v2 extension ecosys'
    conanRepo: 'ado-extension-test-repo1-1687937455'
    purgeExistingRemotes: false
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    tasks: 'artifactoryPublish'
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    tasks: 'artifactoryPublish'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    


    
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'jfrog v2 extension ecosys'
    targetResolveReleaseRepo: 'maven-virtual'
    targetResolveSnapshotRepo: 'maven-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
