name: "Compisite test"
description: "Artifactory"
inputs:
  artifactory-user:
    required: true
    description: "Secret: username for Artifactory server."
  artifactory-api-key:
    required: true
    description: "Secret: artifactory-api-key for API Artifactory"
  artifactory-url:
    required: false
    description: "URL Artifactory server"
runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ inputs.artifactory-url }}
        JF_USER: ${{ inputs.artifactory-user }}
        JF_PASSWORD: ${{ inputs.artifactory-api-key }}
    - name: Run JFrog CLI
      shell: bash
      run: |
        # Ping the server
        jf rt ping
        # Collect environment variables for the build
        jf c show    
