name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List user repositories
        id: list-repos
        run: |
          OWNER=$GITHUB_REPOSITORY_OWNER
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          API="https://api.github.com"

          # Retrieve repository list using the GitHub REST API
          response=$(curl -s -H "Authorization: token $TOKEN" "$API/users/$OWNER/repos")

          # Loop through the repositories
          echo "$response" | jq -r '.[] | .full_name' | while read -r repo; do
            echo "Repository: $repo"
            
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: '1.16'
            
          done
