name: "JFrog CLI Example"
on: push

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JFrog CLI        
        uses: ./.github/composite
        with:
          JFROG_CLI_LOG_LEVEL: DEBUG
          artifactory-url: ${{ vars.JF_URL }} 
          artifactory-user: ${{ secrets.JF_USER }}
          artifactory-api-key: ${{ secrets.JF_PASSWORD }}
