name: "JFrog CLI Example"
on: 
  push:
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
          # Setup FlyFrog registry with OIDC
      - name: Setup FlyFrog Registry
        uses: jfrog/flyfrog-action@v1
        with:
          url: https://flyfrog.example.com
            
      - name: Setup JFrog CLI        
        uses: ./.github/composite
        with:
          artifactory-url: ${{ vars.JF_URL }} 
          artifactory-user: ${{ secrets.JF_USER }}
          artifactory-api-key: ${{ secrets.JF_PASSWORD }}

      - name: Run JFrog CLI
        shell: bash
        run: |
          # Ping the server
          jf rt ping
