name: "JFrog CLI Example"
on: push

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JFrog CLI        
        uses: ./.github/composite
        with:
          artifactory-url: ${{ vars.JF_URL }} 
          artifactory-user: ${{ secrets.JF_USER }}
          artifactory-api-key: ${{ secrets.JF_PASSWORD }}

      - name: Run JFrog CLI
        shell: bash
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf c show    
