name: "JFrog CLI Example"
on: push

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JFrog CLI        
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_URL: ${{ vars.JF_URL }} 
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          # JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf c show
